### PR TITLE
Eng 2065 optimize build

### PR DESCRIPTION
**Pull request by gesparza3**
This PR updates the build process to run outside of the Docker build.  This should significantly increase the speed of builds locally.

Look for new `npm` scripts that should be useful when developing for Backstage:

- `yarn dev` - Run the application locally with Hot Reload enabled
- `yarn build` - Build `dist/` folder for serving the application
- `yarn docker:build` -  Create a docker image using the repo's `Dockerfile`
- `yarn docker:run` - Run latest docker container with port `7000` forwarded and `.env` read in

This PR also includes a new CI/CD process to deploy Backstage to Azure App Service. Checkout the `.github/workflows` and `tf` folders to see how this is setup(_Heavily inspired by Gratibot_)

### CODE REVIEW

**Comment by gesparza3** [comment]
I've been getting [network issues](https://backstage-toolchain.jenkins.lead.prod.liatr.io/job/liatrio/job/liatrio-backstage/job/ENG-2065-optimize-build/16/console) on the agent installing my dependencies. Not sure why yet

**Comment by Pactionly** [comment]
Was this PR supposed to get the pipeline changes included in it? I don't want to approve this without the pipeline working if so.

Otherwise we can cut the pipeline changes and merge in only the build updates.

**Comment by djtjwillia** [comment]
@anthonygauthier is this branch okay to merge right now, or is it going to get in the way of the backstage upgrade you have in progress?

**Comment by anthonygauthier** [comment]
@djtjwillia I'll take a look at it, but from a quick glance it will get in the way if merged like this. 

There's been a ton of stuff added in backstage over the last 10+ months. I'll salvage what I can from the branch and add it to mine, I do see a lot of cool stuff @gesparza3 :smile:

**Pull request closed without merging**
